### ISSUE TITLE
[ERROR] Unexpected user and password while processing

### ISSUE THREAD

**Issue by dafp-link** [prince89arora/vlt-atom#10]
Hi Prince Arora,
Thanks for creating this package. I've just installed it on Atom 1.25.1 and got this error when right-clicking a project sub-folder and selecting "Pull from CRX". 

I left the default values that show up on the user/password fields when the vlt-atom package is installed. Is there a workaround or fix for this so it doesn't take the default values as an error? Or do I need to change the default user and password that comes with my local AEM?

Thanks for your help.

**Comment by prince89arora** [comment]
Hi dafp-link,

This plugin usses default username and password (admin/admin). If you have a fresh AEM installation and credentials aren't changed, then it should work. 
 Still i can work on on this and check what can be the cause. Please give me some time to do that. 
And let me know if you can provide me full stack trace for this error.

Thanks

**Comment by dafp-link** [comment]
Hi Prince Arora,
Thanks for your prompt reply. I tried vlt-atom on a local AEM installation with unchanged credentials, same as stated on the default field values for user & password.  No stack trace link is provided in the red pop-up from the error.

**Comment by prince89arora** [comment]
dafp-link,

Thanks for raisign the issue. I have pusched the patch for this. Please upgrade to 2.2.1.
And let me know if you find any other issue.

Thanks

**Comment by dafp-link** [comment]
Hi Prince Arora,
Thanks for pushing that update. I upgraded it to version 2.2.1 and now I get a different error when trying to pull from CRX (screenshot attached).  Seems like vlt-atom tries to autocomplete the host/ip string with a path that doesn't exist in my local AEM. Is the hyphen needed before jcr:root?  (e.g. extracted from the error message attached: "Checkout http://localhost:4502/crx/-/jcr:root/") . But the correct path where my local index sits has an extra string/folder name after "crx".  So... just an idea and I'll completely understand if this is not how you meant it to work, but, would it be possible to have a field where we can enter the complete path to our localhost (including the port and root index together), instead of having two separate fields to specify the host and port? Plus there's also that JAVA error. I'll do some research and will let you know if I can find anything about that.

Thanks for your constant response.

![vlt-atom-error](https://user-images.githubusercontent.com/10628568/38649787-dcb70558-3e3b-11e8-9355-fe20bc1d5bf3.png)

**Comment by prince89arora** [comment]
Hi dafp-link,

Please go to View > Developer > Toogle Develope Tool. This will open console for atom. You will get the actual command for pull there. Please past that command for me so i can check.

It seems like authentication parameters are not added to access crx repository.

Thanks,

**Comment by dafp-link** [comment]
Hi Prince Arora,
I found what the issue was and came back to share the info with you. This issue was resolved by opening the local project folder from the level where we can see both the **jcr_root** and **META-INF** folders listed. In my case it's from "content". Please see picture attached. 

![jcr_root and meta-inf folders level](https://user-images.githubusercontent.com/10628568/38786107-3031b022-4169-11e8-90d3-bd85941e3958.png)

After searching around a bit I found this tutorial on a similar plugin that was created for the Brackets editor, there's a mention there about opening the project folder at that level mentioned above so I did the same in Atom and then your package synchronised my changes with my local CRX just fine without any errors. :)

Here's the link to the tutorial just for your reference although it's for a different editor, it helps avoid the same issue. The author of the video emphasises about this at minute 3:16.
https://www.youtube.com/watch?v=sqIL3JiZeLw

Thanks a lot for your time and prompt responses. It's all good now.  👍 

Best regards,
Dafp-link.

**Comment by prince89arora** [comment]
Hi Dafp-link,

Yes, we need to open project above jcr_root and META_INF. Reason is, vlt uses these folders and some files to sync content with your crx server.

Again,  thank you for raising this issue. I will make sure this is mentioned in instructions.

Thanks,

**Comment by prince89arora** [comment]
Instructions added in v2.3.0
