### ISSUE TITLE
Bug: Sync Service works intermittently

### ISSUE THREAD

**Issue by dafp-link** [prince89arora/vlt-atom#11]
Hi Prince Arora,
I've been using this package for a few days and noticed that the Sync Service that automatically pushes changes to CRX in the background doesn't work initially when I open Atom. The Sync Service checkbox is checked all the time though. If I then uncheck and check it again, the automated sync starts working. But it stops working every time I close and re-open Atom so then as a workaround I do the unchecking/checking for it to work again every time I open Atom. Just letting you know about this bug.  Thanks for your attention.
dafp-link

![syncserviceerror](https://user-images.githubusercontent.com/10628568/38963909-8f5920bc-43b7-11e8-96c6-7ca9e0bee357.png)

**Comment by prince89arora** [comment]
Thanks Dafp-link, I will defiantly address this issue in next relaese.

**Comment by prince89arora** [comment]
resolved in v2.3.0
