### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by ivanmascolo** [prince89arora/vlt-atom#12]
It doesn't work

**Comment by prince89arora** [comment]
Hi ivanmascolo, Let me know what issue you are facing

**Comment by ivanmascolo** [comment]
If you use WIN OS and into VTL base path have a folder with space inside, the plugin says always successful, but it doesn't do anything. Now I changed the folder name and it's working. Before to push a file on CRX I have to put the file/folder under VTL control, this is not great, I'd like to push a file easier.

Anyway, now it works.
Thank you so much for your support
Have a nice day.
