### ISSUE TITLE
Sync issue on Windows

### ISSUE THREAD

**Issue by schumacher-cgn** [prince89arora/vlt-atom#6]
Just installed vlt-atom 1.1.1 on Windows and have an issue.
Configured this Vlt Base Path: c:/users/demouser/tools/vault-cli-3.1.38

Now, when I do a pull or a push from CRX, I get this error:
"Error: Command failed: cd /C c:\temp\vault-test\weretail && c:/users/demouser/tools/vault-cli-3.1.38\bin\vlt up .\jcr_root\components\structure\header\header.html The filename, directory name, or volume label syntax is incorrect."

**Comment by prince89arora** [comment]
Can you please share full path to header.html file?

**Comment by schumacher-cgn** [comment]
Yes, here we go:
c:\Temp\vault-test\weretail\jcr_root\components\structure\header

**Comment by prince89arora** [comment]
Your path is not correct. 
weretail\jcr_root\components\structure\header

1. This path is suppose to be like weretail\src\main\content\jcr_root\ ... this should be a content package.
2. There is components directory after jcr_root. You are missing your project directory (/apps/<project>). 

Please make sure you have right project structure. And if you still face any issue, i will be happy to help you.

Thanks

**Comment by schumacher-cgn** [comment]
OK, thanks a lot. I changed the path, but without success. Same error.

When I copy the command in the Windows command prompt I get the same error, until I remove the

/C

from the commmand.

**Comment by prince89arora** [comment]
I will try to reproduce it and close this issue after fixing it.

Thanks

**Comment by prince89arora** [comment]
Resolved in 1.2.3.
