### ISSUE TITLE
Vault base is not configured. Please configure vault base to use Vlt Atom

### ISSUE THREAD

**Issue by AnuSaneja** [prince89arora/vlt-atom#9]
Hi,
I am using vlt for sublime, but now i want to use it for Atom. while pushing/pulling anything its gives an error .i.e. "Vault base is not configured. Please configure vault base to use Vlt Atom"

Can anyone help me about this ?

Thanks

**Comment by prince89arora** [comment]
Hi,

This means you need to configure vlt base from your file system. You just need to copy pase the path from your file system in the respective field for this package settings.

vlt zip is shipped with AEM it self. 
<path-to-aem-base>/crx-quickstart/opt/filevault

Hope this will be helpfull.

Thanks

**Comment by AnuSaneja** [comment]
Hi,

Thanks for your reply.
But i could not understand that which path should i have to give in Vlt Base. is it my project path or something else ?

Best Regards

**Comment by prince89arora** [comment]
This option is to tell the package location of your vlt tool. It will use the same vlt location to execute vlt commands.

Thanks

**Comment by AnuSaneja** [comment]
Thanks, its working now

**Comment by prince89arora** [comment]
Great! 
I am closing this issue now. Let me know if you need anyother support.

Thanks
